# DVC data processing pipeline

stages:
  download-ruwiki:
    cmd: scripts/download_russian_wiki_dump.sh
    outs:
      - data/ruwiki-latest-pages-articles.xml.bz2
  download-eyo-dicts:
    cmd: scripts/download_eyo_kernel_dicts.sh
    outs:
      - data/not-safe.txt
      - data/safe.txt
  extract-segments-from-wiki:
    cmd: python scripts/extract_segments_from_wiki.py -n ${data.num-segments}
    deps:
      - data/ruwiki-latest-pages-articles.xml.bz2
    outs:
      - data/ruwiki-yo-segments.txt
  prepare-segments-dataset:
    cmd: python scripts/prepare_segments_dataset.py --max-text-length ${data.max-text-length}
    deps:
      - data/ruwiki-yo-segments.txt
    outs:
      - data/ruwiki-yo-segments-preprocessed.csv
  split-dataset:
    cmd: python scripts/split_dataset.py
    deps:
      - data/ruwiki-yo-segments-preprocessed.csv
    outs:
      - data/train.csv
      - data/test.csv
