[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["tests"]
python_files = "test_*.py"
addopts = "--strict-markers --disable-pytest-warnings"
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
